### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by maxwellt0** [vHotsuliak/ClinicPetWebDB#1]
https://github.com/vHotsuliak/ClinicPetWebDB/blob/d3eb3e9fdae5ee8b33d3545934ee5f5cffe26ac4/src/main/java/com/models/Client.java#L50

Possible NullPointerException at "this.pet.getClass()"

**Comment by vHotsuliak** [comment]
The expression `x instanceof SomeClass` is `false` if `x` is `null`.
https://github.com/vHotsuliak/ClinicPetWebDB/blob/608494ba6244600a04ba527562cd18c7cd403646/src/main/java/com/models/Client.java#L66
