### ISSUE TITLE
createStatement is not secure

### ISSUE THREAD

**Issue by maxwellt0** [vHotsuliak/ClinicPetWebDB#2]
https://github.com/vHotsuliak/ClinicPetWebDB/blob/d3eb3e9fdae5ee8b33d3545934ee5f5cffe26ac4/src/main/java/com/store/JDBCStorage.java#L71

Better to use prepareStatement that createStatement. Use of createStatement is completely insecure.
Check this explanation: https://stackoverflow.com/questions/3271249/difference-between-statement-and-preparedstatement

**Comment by vHotsuliak** [comment]
https://github.com/vHotsuliak/ClinicPetWebDB/blob/608494ba6244600a04ba527562cd18c7cd403646/src/main/java/com/store/JDBCStorage.java#L67
